### ISSUE TITLE
TO-DO list

### ISSUE THREAD

**Issue by SiyangHe2017** [SiyangHe2017/Tetris#1]
# to do list
- [ ] when the player fail, stop and wait for the player choosing replaying or closing the game instead of exit
- [ ] set the time of the game
- [ ] set the maximum of the player
